import useUser from '../lib/useUser'
import useLicense from '../lib/useLicense'
import useSWR from 'swr'
import Layout from '../components/Layout'
import License from '../components/License'

const SGLicense = () => {
  const { user } = useUser({ redirectTo: '/login' })
  if (!user || user.isLoggedIn === false) return <div></div>

  // const { license } = useLicense({})
  // const { data: license } = useSWR("/api/license")

  return (
    <Layout>
      <h1>License SG2</h1>
      <h3>Rendered using component</h3>
      {/* {!license && <p>Loading...</p>} */}
      {/* {license && (
        <pre className="pre">{JSON.stringify(license, undefined, 2)}</pre>
      )} */}
      <License />
      <h3>Lorem ipsum</h3>
      <p>Lacus pulvinar eleifend commodo mi orci habitant quis class, metus aptent dui hac nascetur dictum neque vulputate, fusce nec ultricies ullamcorper ligula eu fermentum accumsan facilisis, duis dolor odio fringilla vehicula turpis penatibus. Vel nascetur sit fringilla molestie bibendum lacus augue tincidunt euismod, facilisis montes torquent purus erat urna conubia adipiscing lacinia, semper vitae id praesent mattis pellentesque nec consectetur elementum fusce, gravida iaculis venenatis ac tortor sem aliquam non. Sociosqu per eros curae interdum tellus natoque neque pulvinar primis, nec pretium nunc velit ultricies vestibulum egestas ac nascetur, fringilla metus diam netus venenatis cursus suscipit turpis, class gravida praesent mollis sollicitudin taciti parturient ligula. Primis lacus praesent natoque sit nam lobortis volutpat augue, litora parturient magna ligula imperdiet aliquam nibh dolor fusce, viverra efficitur per ipsum enim curae eleifend arcu ornare, libero orci quam sapien netus conubia nisi. Proin mollis dictum vestibulum enim habitasse nunc facilisi mauris, congue lacinia placerat vulputate est duis nascetur auctor, tincidunt augue magna nisl himenaeos scelerisque egestas nisi sollicitudin, lectus volutpat iaculis facilisis sed penatibus interdum. In magnis nisi nunc laoreet mollis fames consequat orci iaculis, porttitor at luctus tellus ut ultrices praesent id fringilla, vestibulum ad sollicitudin phasellus morbi semper rutrum gravida, pretium hendrerit class viverra nisl urna sem feugiat. Accumsan tortor elementum auctor per id blandit mauris eget praesent, dictumst ultrices nullam ex curae pharetra ipsum sapien litora, etiam euismod netus pretium lobortis massa in placerat mus, neque himenaeos magna non consequat vivamus elit nam. Ac class bibendum magna arcu a primis nisi maximus, ullamcorper facilisi eros potenti in nunc elit ipsum, posuere scelerisque torquent penatibus ligula turpis viverra efficitur, condimentum proin leo quis nulla quisque ex.</p>
      <p>Eros duis in nibh platea diam ultricies penatibus faucibus hendrerit vehicula, sapien malesuada interdum aptent lorem velit primis sollicitudin porta arcu, lacus himenaeos eget massa sagittis aliquam egestas ex sociosqu, finibus praesent ante dolor vel vulputate efficitur quis accumsan. Duis sapien efficitur mi nibh elit euismod facilisis tortor tellus facilisi, semper sit cursus egestas rutrum sem lobortis nec bibendum leo, et tristique ipsum eget eu condimentum sagittis sed laoreet consectetur, parturient habitant finibus torquent dolor vivamus justo netus praesent. Urna ligula montes natoque habitant nibh malesuada fringilla justo semper leo, tempus aliquet dignissim est rhoncus lectus sociosqu imperdiet ornare dictumst, metus sollicitudin praesent class consequat porta mus potenti sagittis netus, placerat sit consectetur at eget iaculis lorem phasellus habitasse. At dolor aliquam efficitur tortor vitae fusce nibh finibus, vulputate tristique risus purus dis enim nullam morbi proin, ornare inceptos cursus ex potenti commodo habitasse parturient egestas, faucibus magnis primis ut nisi etiam pharetra. Iaculis hac aenean eu dictum varius eget faucibus sapien, nam turpis auctor rhoncus suscipit luctus vulputate platea et, purus curae enim dis pulvinar vivamus nibh scelerisque massa, orci fringilla ex tellus duis quisque est. Ullamcorper iaculis a purus phasellus varius duis ut pellentesque finibus, arcu natoque sociosqu metus facilisi lacinia euismod sem scelerisque, platea mattis rhoncus faucibus at proin vulputate curabitur, suspendisse fermentum ridiculus pharetra turpis egestas etiam maximus. Mi litora commodo luctus eros nisi augue quis congue, fermentum eu venenatis orci sodales praesent tellus aliquet curabitur, ultrices nam dignissim parturient senectus tincidunt sociosqu est purus, maecenas tortor netus aliquam interdum faucibus suspendisse. Ridiculus nam rutrum risus facilisi vestibulum dictum duis praesent phasellus, fermentum quam fames tincidunt dictumst hendrerit iaculis lobortis sapien, parturient aliquet malesuada eleifend ex arcu erat mi, nec curae molestie ipsum cubilia nisi ligula neque. Laoreet aenean sed mauris amet mus nisi ipsum eu, est dignissim vitae convallis ex magnis hendrerit phasellus, imperdiet justo habitant pulvinar dictumst velit dis consequat, facilisi nam vehicula nostra sollicitudin varius sociosqu. Ac lacinia eleifend ornare arcu quam scelerisque ullamcorper vivamus, elit justo torquent suscipit malesuada habitasse inceptos iaculis, eget dictumst neque fermentum per nam blandit donec dis, euismod varius lacus conubia volutpat sociosqu litora.</p>
      <p>Nulla viverra consequat ipsum suspendisse quisque amet turpis mollis pulvinar, phasellus molestie sem fusce eros mattis lectus varius placerat, dis gravida auctor sagittis ac sapien nascetur ad sed, non lobortis orci aptent himenaeos nostra metus ultrices. Dolor ultricies tortor posuere tempus blandit turpis diam fermentum fusce, commodo mollis penatibus fringilla pellentesque lacinia imperdiet tincidunt scelerisque, parturient eu at nullam velit consequat nascetur mi, netus efficitur a quam vehicula mauris vel dapibus. Faucibus fermentum dignissim enim magnis aptent bibendum luctus feugiat, pharetra nostra curae habitant id inceptos ut lacinia arcu, potenti tellus tortor ullamcorper risus nibh himenaeos neque eleifend, dolor convallis purus porta semper dictumst vehicula. Aliquam fermentum inceptos consequat faucibus nunc ante pulvinar primis dui, magna cras aliquet netus fusce cubilia maecenas condimentum phasellus, etiam conubia platea turpis libero risus penatibus neque, odio non egestas metus varius ridiculus eu praesent. Etiam ligula dictumst interdum turpis elit potenti ornare nunc, id lacus tellus elementum mauris facilisis ultricies vestibulum, vel nam molestie ut luctus maximus tortor euismod tempus, consequat dictum mattis pharetra habitasse commodo bibendum. Aenean elementum fusce malesuada enim conubia curae ultrices et, fermentum metus aliquam porttitor semper nostra a erat ornare, aptent convallis phasellus eget senectus vitae fames in class, gravida condimentum dis ipsum odio morbi curabitur. Sodales odio torquent id aptent tristique cubilia pulvinar vestibulum, fames morbi finibus sociosqu tortor rhoncus semper fusce elit, primis sed libero risus leo a aliquet quisque tempus, egestas malesuada auctor duis ridiculus habitant platea. Senectus fringilla eu netus efficitur ipsum facilisi felis mauris consectetur, condimentum non mi fusce cursus nec curabitur per natoque, dignissim ut accumsan sapien viverra malesuada duis metus, ex rhoncus lacus ad sagittis conubia pretium ultricies. Enim pharetra erat pulvinar vitae hac aliquam urna inceptos, sodales pellentesque vestibulum nascetur turpis euismod cras posuere, at parturient fusce maximus tempus imperdiet eget primis rutrum, proin duis nec massa sapien nulla consectetur.</p>
    </Layout>
  )
}

export default SGLicense
