import useUser from '../lib/useUser'
import Layout from '../components/Layout'
import License from '../components/License'
// import Projects from '../components/Projects'
// import MyProjects from '../components/MyProjects'

const SgProfile = () => {
  const { user } = useUser({ redirectTo: '/login' })

  if (!user || user.isLoggedIn === false) {
    return <div></div>
  }

  return (
    <Layout>
      <h1>Profile SG</h1>
      <h3>
        useUser via /api/user dengan hook withSession
      </h3>

      <pre className="pre">{JSON.stringify(user, undefined, 2)}</pre>

      {/* <License /> */}

      <h3>Lorem ipsum</h3>
      <p>Sodales enim dictumst penatibus eu cursus ante potenti ac, aptent a phasellus convallis mi rhoncus per lectus torquent, gravida dictum nec litora ridiculus diam eget sagittis proin, eleifend nunc varius tristique lobortis accumsan pulvinar. Eleifend aliquet fames penatibus cubilia venenatis finibus nibh mollis sem, justo ante felis senectus tincidunt molestie sollicitudin ipsum orci, porttitor gravida libero fermentum neque phasellus mus pellentesque, luctus diam blandit dolor augue sit conubia nam. Ultrices varius euismod facilisi finibus habitant nisl pellentesque cursus, lorem ligula volutpat laoreet magna mus lectus ad, aliquam massa id at sagittis eu egestas semper tincidunt, venenatis vitae mi ultricies phasellus diam duis. Mus senectus ultricies sagittis duis tempor libero quis fusce malesuada, habitant aptent nascetur nunc blandit varius class pulvinar vivamus, convallis aenean velit egestas dui eleifend enim et, at conubia nostra lacus in porta netus phasellus. Lobortis faucibus aptent cras nunc venenatis etiam massa et, primis sem tempor suspendisse mollis ac penatibus sed senectus, donec curabitur phasellus torquent nullam rutrum suscipit luctus dolor, imperdiet sociosqu odio adipiscing maximus potenti quisque. Pretium vivamus sociosqu taciti aenean placerat maximus ligula accumsan lorem, blandit dapibus suscipit eu facilisis himenaeos natoque lacinia porta, fringilla sollicitudin condimentum odio scelerisque morbi quis conubia, dis sed phasellus rhoncus mus leo augue posuere. Sem mauris praesent ligula sapien luctus sed class scelerisque, ipsum platea commodo rutrum montes condimentum iaculis torquent lectus, dictum vehicula felis consequat id orci aptent placerat faucibus, pulvinar in aliquam nulla viverra fames maximus. Primis ex odio blandit velit donec lorem accumsan urna, id proin nam sit nunc ridiculus sed imperdiet morbi, penatibus potenti tortor senectus amet mus massa dictum aliquet, neque sapien eu parturient quam arcu purus. Non iaculis hendrerit pulvinar metus cursus ac ullamcorper urna efficitur, aliquam posuere finibus neque facilisis consectetur penatibus augue accumsan, praesent sapien elementum orci erat ex nullam ad imperdiet, nunc dapibus faucibus etiam commodo quisque eget massa.</p>
      <p>Est molestie vehicula mollis lobortis iaculis per donec aliquet tincidunt, sodales gravida cubilia curae pretium feugiat rhoncus quisque quis, sem mattis senectus pellentesque ultrices dis ante inceptos fusce facilisis, eget metus parturient dolor sit varius ullamcorper luctus. Consequat phasellus mattis justo ligula hendrerit massa per praesent rutrum, eleifend proin ultricies consectetur commodo convallis neque ex pretium, netus ornare porttitor dictumst arcu diam himenaeos scelerisque, quam posuere odio eget aptent aenean dolor elit. Ridiculus ornare aliquam phasellus tristique congue eget ultricies commodo id, ut conubia pellentesque platea orci mollis aenean enim et, netus suspendisse nulla ipsum varius feugiat nascetur augue, taciti lacus egestas inceptos ex leo fames praesent. Donec dui non ligula tellus efficitur turpis etiam sociosqu, dictumst dis ante luctus lacus sit porttitor nec amet, semper elit est praesent fermentum laoreet gravida ullamcorper justo, natoque aliquam molestie euismod pretium suscipit sed. Morbi hac sociosqu class senectus taciti facilisis porta habitant, platea dignissim sapien magna erat habitasse molestie montes vel, fringilla libero cubilia tempor vivamus adipiscing primis ad eros, ac risus fusce praesent quis duis eu. Platea torquent lobortis nascetur lacus sociosqu fermentum nunc vulputate, rutrum dolor tempus arcu sapien parturient pulvinar pretium himenaeos, quis magna laoreet viverra ante scelerisque nam adipiscing eu, molestie elit est proin vestibulum penatibus finibus. Semper curae placerat senectus sociosqu nec augue iaculis pretium nulla, mattis convallis lectus vivamus elementum porttitor penatibus efficitur et, curabitur pharetra accumsan neque condimentum aliquet dolor vulputate, rutrum pellentesque molestie nisl leo magna nibh urna. Vitae ullamcorper pellentesque conubia accumsan eget nam fermentum pulvinar felis, magnis sit tortor facilisis luctus euismod elit torquent aenean, vivamus lacinia pharetra nascetur nunc maecenas curabitur malesuada, sed natoque metus urna etiam curae dictum ridiculus. Laoreet dis nascetur urna vulputate metus sagittis nec ac, eleifend lacinia aliquet sed suspendisse nisl vel class, maximus consectetur praesent potenti aptent eu ornare maecenas donec, dolor amet aenean volutpat ut dui mattis.</p>
      <p>Dapibus auctor cras aptent posuere litora lacus netus consequat, penatibus vitae sapien euismod morbi interdum scelerisque blandit, imperdiet finibus aliquam velit metus vel laoreet phasellus, molestie arcu pharetra mauris tellus suscipit eleifend. Dignissim laoreet natoque arcu maximus commodo curae non euismod, viverra ridiculus gravida dis cursus per at sit malesuada, maecenas congue duis enim bibendum aliquet venenatis fusce taciti, in penatibus tempor porttitor suspendisse ad dapibus. Ex ac lectus cubilia ultricies habitant purus pulvinar etiam, natoque scelerisque libero ultrices vel nostra senectus lacinia accumsan, pellentesque interdum inceptos suspendisse quam sagittis odio tellus ullamcorper, hendrerit iaculis potenti porta fames sem dictumst. Dapibus morbi tellus tincidunt mollis quam facilisis metus commodo platea, venenatis facilisi aliquet pretium hendrerit ac parturient cubilia conubia, mauris vehicula gravida sed curabitur vestibulum mattis ex suscipit, aptent malesuada eu integer libero vel dui elementum. Massa vitae penatibus condimentum egestas fames senectus elit platea quam, augue donec ligula tincidunt aliquet dapibus ex interdum tempor, nisi ipsum pharetra et tortor sodales hendrerit duis etiam, fringilla auctor netus consectetur est nascetur quisque commodo. Libero curae vehicula natoque curabitur congue mattis cubilia scelerisque porta ante, lacus ullamcorper augue diam metus odio lectus tortor ad molestie, eros malesuada nisl iaculis magnis aliquam euismod sollicitudin turpis interdum, magna placerat ultrices aenean hendrerit aptent inceptos fringilla cursus. Vehicula habitant nostra diam tellus curae blandit nam conubia, pretium sed mus sagittis consectetur nascetur praesent maximus, sociosqu commodo pharetra vivamus torquent justo at dictumst, aliquam aliquet sapien ultrices cursus aptent lacus. Nostra dui iaculis eget cras et a non pulvinar neque, adipiscing faucibus tincidunt montes egestas phasellus arcu pellentesque hendrerit, commodo amet pretium fringilla efficitur blandit facilisi class sagittis, tortor sodales hac aptent ex ipsum elit malesuada. Praesent netus euismod dis sociosqu ut lacus quam nibh accumsan, libero pretium ad in natoque tristique inceptos aptent ultricies, donec felis tellus rutrum dictum sem augue vestibulum ipsum, ligula massa congue ornare nisl eget fames fringilla.</p>
    </Layout>
  )
}

export default SgProfile
